### ISSUE TITLE
Action Plugin doesn't work on macOS (13.6.9)

### ISSUE THREAD

**Issue by Cocoader** [snhobbs/kicad-parts-placer-pcm#1]
### Describe the bug
The Action Plugin doesn't show up in the menu bar or Tools / External Plugins.

### Desktop (please complete the following information):
OS: macOS Ventura 13.6.9
KiCad 8.0.4 with bundled Python 3.9.13

### Additional context
I did try it in a Windows 10 VM with KiCad 8.0.4 with bundled Python 3.11.5 which worked.
I did also try another plugin of yours - **kicad-testpoints-pcm** - on macOS which worked as well.
I don't understand why KiCad is still bundling such an old version of python and doesn't use the same version for Windows and macOS.
Hopefully you can reproduce this in 3.9.13.

**Comment by snhobbs** [comment]
Ah yeah it's just the typing syntax of type unions. A couple people on python 3.8 complained too, should be able to swap that out this week.

**Comment by Cocoader** [comment]
Thank you very much for the fast reply and the estimation for the fix. I do appreciate your good work.

**Comment by Cocoader** [comment]
I know you're probably busy, but I was wondering if you had a chance to look into it?

**Comment by snhobbs** [comment]
Try this one out: https://github.com/snhobbs/kicad-parts-placer-pcm/releases/download/v0.1.3/kicad-parts-placer-0.1.3-pcm.zip

From the PCM you can do install from file and then just select the zip

**Comment by Cocoader** [comment]
Thank you for the fast reply. 
I did try it but unfortunately it still doesn't show up.
![Screenshot 2024-09-10 at 02 02 05](https://github.com/user-attachments/assets/ccc403f7-341e-4c51-9683-996fa1c0cd6f)
![SCR-20240910-cqyh](https://github.com/user-attachments/assets/eb4862d4-f713-4ecd-a211-53844b0dc6cb)

**Comment by snhobbs** [comment]
Okay, the fact you had kicad-testpoints installed really helped. Try this version: https://github.com/snhobbs/kicad-parts-placer-pcm/releases/download/v0.1.4/kicad-parts-placer-0.1.4-pcm.zip

**Comment by Cocoader** [comment]
That did the trick. Thanks a lot for the swift fix. I do appreciate your work for the open source community.
