### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by Cocoader** [snhobbs/kicad-parts-placer-pcm#2]
There are two minor UI improvements with the dialog box.

1. Draw the dialog box to fit the context on open
2. Remove the overlapping "Sub" label

macOS:
![mac](https://github.com/user-attachments/assets/71f5277e-5e3c-4bda-8883-fc8944559199)

Windows 10 VM:
![win10](https://github.com/user-attachments/assets/1441079e-e152-4b82-bd0b-2bb8e69443c3)

This also applies to some extent to your other plugin, **'Test Point Report'**, where the buttons are easily accessible, and only the hint is truncated. I don't think this is worth another issue if you label this as _won't fix_.

**Comment by snhobbs** [comment]
I appreciate the issues! You can tell I'm only testing in Linux...

Here's the updated release! https://github.com/snhobbs/kicad-parts-placer-pcm/releases/download/v0.1.5/kicad-parts-placer-0.1.5-pcm.zip

Tested on Windows & Ubuntu.

**Comment by Cocoader** [comment]
>I appreciate the issues! You can tell I'm only testing in Linux...

I just wanted to check if I can bother you with UI / UX stuff - I figured you're using linux.

> 2. Remove the overlapping "Sub" label

This is resolved - great.

> 1. Draw the dialog box to fit the context on open

Does the dialog window open with the buttons and text fields visible for you? 
In macOS I have to resize it every time and in Windows I have to either move the window or resize it. It always opens in this collapsed view.

**Comment by snhobbs** [comment]
How's this? 
https://github.com/snhobbs/kicad-parts-placer-pcm/releases/download/v0.1.6/kicad-parts-placer-0.1.6-pcm.zip

**Comment by Cocoader** [comment]
>How's this?
https://github.com/snhobbs/kicad-parts-placer-pcm/releases/download/v0.1.6/kicad-parts-placer-0.1.6-pcm.zip

Works like a charm on macOS and Windows - much appreciated.

Those fixes could also apply to some extent to your other plugin _kicad-testpoints-pcm_. 

 It's great to see how quickly you addressed this issue.

**Comment by snhobbs** [comment]
Thanks for the input and testing! Feedback and features suggestions are also welcome!
