### ISSUE TITLE
Change in placement file format

### ISSUE THREAD

**Issue by Cocoader** [snhobbs/kicad-parts-placer-pcm#3]
Could it be possible that kicad changed the format of the placement file (**File / Fabrication Outputs / Component Placement (.pos, .gbr.)...**) from

![Screenshot 2024-09-11 at 02 18 13](https://github.com/user-attachments/assets/f7036d05-6e04-4c57-8ec3-9c65e1ecce93)
 

`"ref des","value","Package","x","y","rotation","side","show ref des","show value"`
https://github.com/snhobbs/kicad-parts-placer/blob/master/example/example-placement/centroid-all-pos.csv#L1

to 

`Ref,Val,Package,PosX,PosY,Rot,Side`
https://github.com/snhobbs/kicad-parts-placer/blob/master/example/example-placement/example-placement_placed-all-pos.csv#L1

at some point - maybe v8, or are you exporting your centroid file differently?

Manually changing the currently exported header from `Ref,Val,Package,PosX,PosY,Rot,Side` to `"ref des","value","Package","x","y","rotation","side"` let's me import it via the plugin.

Can you reproduce this?

**Comment by snhobbs** [comment]
Yeah, we can add a list of different centroid header formats or add a list of pseudonyms for each column. For other tools that export centroid/position files they could use this same selection of header formats to support interchange (KICAD-make and kicad-testpoints specifically).

**Comment by Cocoader** [comment]
Sounds good. 
I find your pseudonyms approach for front and back quite elegant and easily expandable if used for all header variables. https://github.com/snhobbs/kicad-parts-placer/blob/4e2edb77cad9592c8e9ad6049c220ecf3b0be4d4/src/kicad_parts_placer/kicad_parts_placer.py#L194

**Comment by snhobbs** [comment]
v0.1.10 adds the aliases so it supports several centroid formats now.

https://gitlab.com/snhobbs/metadata/-/jobs/7826655144/artifacts/raw/artifacts/repository.json

**Comment by Cocoader** [comment]
Brilliant - thank you very much for the swift implementation. I'm eager to test it.

>https://gitlab.com/snhobbs/metadata/-/jobs/7826655144/artifacts/raw/artifacts/repository.json

Did you paste this link by mistake?

**Comment by snhobbs** [comment]
No that's the json for adding the pcm repo. Press manage next to the repo in the pcm window and you can add it.

**Comment by Cocoader** [comment]
Oh I didn't know you can add additional repos - besides the official one - directly in KiCad.

The install mechanism works but unfortunately it doesn't show up in the menu (macOS and windows10) like in one of your past versions.
![Screenshot 2024-09-15 at 00 56 23](https://github.com/user-attachments/assets/67ef693f-5f48-49b8-af12-313d82ad25c8)

![SCR-20240915-bued](https://github.com/user-attachments/assets/3b572be5-f2d0-40ea-8258-a070f72a2db0)

**Comment by snhobbs** [comment]
Ah. Right: Update: https://gitlab.com/snhobbs/metadata/-/jobs/7826906847/artifacts/raw/artifacts/repository.json

**Comment by Cocoader** [comment]
Thank you for the fast reply. I think there is some regression going on now.
The Windows10 plugin can be installed now but the window size has the behaviour from before [v0.1.6](https://github.com/snhobbs/kicad-parts-placer-pcm/releases/tag/v0.1.6).
In macOS the plugin still doesn't launch / show up.

**Comment by Cocoader** [comment]
Thank you very much. I think I didn't have enough coffee and it either defaulted back to v0.1.2 or I miss-clicked - hence the deleted message.
This works perfectly with both formats and should be easily expandable for any centroid format (other EDA tools).
I appreciate your fast solution.
